---
- name: Install and run Jenkins on CentOS servers
  hosts: all
  become: true

  tasks:
    - name: Install Java (Jenkins dependency)
      yum:
        name: java-11-openjdk
        state: present

    - name: Add Jenkins repository
      yum_repository:
        name: Jenkins
        description: Jenkins repo
        baseurl: http://pkg.jenkins.io/redhat-stable/
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Ensure firewall allows Jenkins
      firewalld:
        service: jenkins
        permanent: yes
        state: enabled
        immediate: yes

    - name: Restart firewalld to apply changes
      systemd:
        name: firewalld
        state: restarted
